assessment/urls.py
from django.urls import path
from .views import (AssessmentQuestionGroupDetailView, CreateMultipleChoiceQuestion, DeleteQuestionGroup,
                    QuestionGroupCreateView, CreateTheoryQuestion, EditTheoryQuestion,
                    DeleteQuestion, MultiChoiceQuestionEdit, AssessmentView,
                    ConductAssessment, AssessmentPreferenceCreateView,
                    ConductingAssessment, StudentAssessmentView, LectureStudentScriptTemplateView,
                    QuestionGroupUpdateView, GenerateQMarksRedirectQGroupRV, AssessmentPreferenceUpdateView,
                    StudentAssessingTemplateView, MultiChoiceQuestionsExaminationView, QuestionResultTemplateView,
                    QuestionsPreviewTemplateView, QuestionResultDetailTemplateView, TheoryQuestionsExaminationView,
                    TheoryQuestionAnswerView, TheoryScriptStatusTemplateView, StopAllWorkTemplateView,
                    AddOneMoreTheoryQuestion, StudentCompletedPublishedAssessmentView
                    )


app_name = "assessment"
urlpatterns = [
    path("all/", AssessmentView.as_view(), name="all"),
    path("prepareQuestion/<str:courseName>/<int:coursePK>/", QuestionGroupCreateView.as_view(), name="create_group"),
    path("updateQuestionGroup/<str:courseName>/<int:coursePK>/<str:title>/<int:pk>", QuestionGroupUpdateView.as_view(),
         name="update_group"),
    path("prepareTheory/<str:QGT>/<int:QGPK>/", CreateTheoryQuestion.as_view(), name="prepare_theory"),
    path("preparetheoryplusonemore/<int:question_group_pk>/<str:question_group_title>/<str:questions_type>/", AddOneMoreTheoryQuestion.as_view(), name="add1theory"),
    path("prepareMultichoiceQuestion/<str:QGT>/<int:QGPK>/", CreateMultipleChoiceQuestion.as_view(),
         name="prepare_MCQ"),
    path("questiongroupdetails_detail/<str:courseName>/<str:title>/<int:pk>/",
         AssessmentQuestionGroupDetailView.as_view(), name="question_grp_detail"),
    path("question/update_multichoice_question/<str:group_title>/<int:questionPK>/", MultiChoiceQuestionEdit.as_view(),
         name="update_mcq"),
    path("question/update_theory/<str:group_title>/<int:pk>/", EditTheoryQuestion.as_view(), name="update_theory"),
    path("question/delete/<str:coursePK>/<str:group_title>/<int:pk>/", DeleteQuestion.as_view(),
         name="delete_question"),
    path("question_group/delete/<str:courseName>/<int:coursePK>/<int:pk>/", DeleteQuestionGroup.as_view(),
         name="delete_question_group"),
    path("conduct/<str:question_group_title>/<int:question_group_pk>", ConductAssessment.as_view(), name="conduct"),
    path("preference/<str:question_group_title>/<str:question_group_pk>/", AssessmentPreferenceCreateView.as_view(),
         name="preference"),
    path("preference/<str:question_group_title>/<str:question_group_pk>/<int:pk>/",
         AssessmentPreferenceUpdateView.as_view(), name="preference_update"),
    path("conducting_test/<str:course_name>/<int:question_group_pk>/<int:course_pk>/", ConductingAssessment.as_view(),
         name="conducting"),
    path("conducting_test/preview_question/<str:question_group_title>/<str:question_group_pk>/",
         QuestionsPreviewTemplateView.as_view(), name="pre_questions_conducting"),

    # Assessment URLS
    path("student/view/", StudentAssessmentView.as_view(), name="student"),
    path("student/view/<str:course_code>/<str:course_name>", StudentCompletedPublishedAssessmentView.as_view(), name="completed_published_assessment4student"),

    path("lecture/student/script/<int:course_id>/<int:question_group_id>/<int:student_id>/<str:questions_type>/",
         LectureStudentScriptTemplateView.as_view(), name="lecture_student_script"),
    path("generateMarks/<str:QGT>/<int:QGPK>/", GenerateQMarksRedirectQGroupRV.as_view(), name="generate_marks"),
    path("student/HALL/<str:QGT>/<int:QGPK>/", StudentAssessingTemplateView.as_view(), name="student_assessing"),

    # Exam
    path("scripts/multichoice/start/<str:course_code>/<str:QGT>/<int:QGPK>/",
         MultiChoiceQuestionsExaminationView.as_view(), name="MCQ_exam_start"),
    path("scripts/theory/start/<str:question_group_title>/<int:question_group_id>/<str:semester>/",
         TheoryQuestionsExaminationView.as_view(), name="theory_exam_start"),
    path("scripts/theory/answer/<str:question_group_title>/<int:question_group_id>/<int:script_pk>/<int:question_pk>/",
         TheoryQuestionAnswerView.as_view(), name="theory_exam_answer"),
    path("examiniation/theory/scripts/<int:script_pk>/", TheoryScriptStatusTemplateView.as_view(),
         name="theory_exam_status"),

    # STOP ALL WORK
    path("examiniation/<int:question_group_pk>/<int:course_id>/<str:question_group_title>/",
         StopAllWorkTemplateView.as_view(), name="exam_stop_all"),

    # Results
    path("scripts/result/summary/<int:student_id>/<int:course_id>/<int:question_group_id>/<int:script_pk>/"
         "<str:questions_type>/", QuestionResultTemplateView.as_view(), name="result"),
    path("scripts/result/details/<int:student_id>/<int:course_id>/<int:question_group_id>/<str:questions_type>/",
         QuestionResultDetailTemplateView.as_view(), name="result_detail"),

]

chat/urls.py
from .views import (
    MessagesCreateView, ChatTemplateView, IndividualChatsTemplateView,
    ChatHistoryRedirectView, CourseMassageChat, ChatPeopleTemplateView,
    SelectedDepartmentProgrammeLevel,
    )
from django.urls import path


app_name = "chat"
urlpatterns = [
    path("start/messaging<slug:to_user_slug>", MessagesCreateView.as_view(), name="start_message"),
    path("add/message<slug:to_user_slug>", ChatHistoryRedirectView.as_view(), name="add_message"),
    path("", ChatTemplateView.as_view(), name="home"),
    path("individualschats/", IndividualChatsTemplateView.as_view(), name="individual_chats"),
    path("individualschats/<int:programme_id>/<int:level_pk>", IndividualChatsTemplateView.as_view(), name="individual_chats4lecture"),
    path("individualchats/<slug:current_user_slug>/", IndividualChatsTemplateView.as_view(), name="individualchats_user"),
    path("individualchats/<slug:current_user_slug>/<int:programme_id>/<int:level_pk>", IndividualChatsTemplateView.as_view(), name="individualchats_user_4lecture"),
    path("course/<int:course_id>/", CourseMassageChat.as_view(), name="course_message"),
    path("course/people/<str:course_code>/", ChatPeopleTemplateView.as_view(), name="course_people"),
    path("individualselection/", SelectedDepartmentProgrammeLevel.as_view(), name="individual_filter_selection"),
]

eAssessmentSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from .view import LandingPage, AboutTemplatePage, SupportTemplatePage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPage.as_view(), name="landing-page"),
    path('about/', AboutTemplatePage.as_view(), name="about-page"),
    path('support/', SupportTemplatePage.as_view(), name="support-page"),
    path("accounts/", include("accounts.urls")),
    path("student/", include("student.urls")),
    path("department/", include("department.urls")),
    path("lecture/", include("lecture.urls")),
    path("assessment/", include("assessment.urls")),
    path("records/", include("record.urls")),
    path("settings/", include("setting.urls")),
    path("chat/", include("chat.urls")),

]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lecture/urls.py
from django.urls import path
from .views import (
    LectureCreateView, LectureDetailView, lecture_created_view, LectureListView,
    LectureStudentScripts, QuizTemplateView, OnGoingQuizTemplateView, QuestionGroupDetailView,
    TheoryMarkingSchemeDetailView, TheoryQuestionSolution, TheoryQuestionSolutionUpdateView,
    TheoryMarkingSchemeHomeTemplateView, MarkTheoryScriptsDetailView, MarkScriptView,
    DepartmentLecturesTemplateView,
)

app_name = "lecture"
urlpatterns = [
    path("add/", LectureCreateView.as_view(), name="add"),
    path("created/", lecture_created_view, name="created"),
    path("detail/<int:pk>/", LectureDetailView.as_view(), name="detail"),
    path("list/", LectureListView.as_view(), name="list"),

    path("assessment/scripts/all/", LectureStudentScripts.as_view(), name="scripts_all"),
    path("assessment/quiz/all/", QuizTemplateView.as_view(), name="quiz_all"),
    path("assessment/quiz/on_going/", OnGoingQuizTemplateView.as_view(), name="on_going_quiz"),
    path("assessment/quiz/detial/<int:question_group_pk>/<int:course_id>/", QuestionGroupDetailView.as_view(), name="question_group_detail"),

    path("assessment/scheme/home/", TheoryMarkingSchemeHomeTemplateView.as_view(), name="scheme_home"),
    path("assessment/scheme/theory/detail/<str:course_id>/<int:question_group_pk>/", TheoryMarkingSchemeDetailView.as_view(), name="theory_scheme_detail"),
    path("assessment/scheme/theory/add/solution/<str:course_id>/<int:question_id>/<int:question_group_id>/<int:scheme_pk>/", TheoryQuestionSolution.as_view(), name="theory_solution_create"),
    path("assessment/scheme/theory/update/solution/<str:course_id>/<int:question_id>/<int:question_group_id>/<int:scheme_id>/<int:solution_pk>/", TheoryQuestionSolutionUpdateView.as_view(), name="theory_solution_update"),

    # marking
    path("assessment/mark/scrpts/<str:question_group_title>/<str:question_group_pk>/", MarkTheoryScriptsDetailView.as_view(), name="mark_scripts"),
    path("assessment/mark/<str:student__index_number>/<int:question_group_id>/<int:student_script_pk>/<int:scheme_pk>/", MarkScriptView.as_view(), name="mark_student_script"),

    # HOD
    path("in/<str:department_name>", DepartmentLecturesTemplateView.as_view(), name="department_lecture"),
]

record/urls.py
from django.urls import path
from .views import (RecordsView, StudentRecordTemplateView,
                    LectureRecordsTemplateView, LectureQuizRecordDetailView, PublishRecordsDetailView,
                    StudentRecordsTemplateView, LectureCourseRecords
                    )


app_name = "records"

urlpatterns = [
    path("all/", RecordsView.as_view(), name="all"),
    path("student/", StudentRecordTemplateView.as_view(), name="student"),
    path("lecture/all/", LectureRecordsTemplateView.as_view(), name="lecture_all"),
    path("lecture/course/<str:course_code>/<int:question_group_pk>/<str:question_group_title>/",
         LectureQuizRecordDetailView.as_view(), name="lecture_quiz_detail"),
    path("publish/<str:question_group_title>/<int:question_group_pk>/<str:course_code>/",
         PublishRecordsDetailView.as_view(), name="publish"),
    path("student/<str:course_code>/<int:course_id>", StudentRecordsTemplateView.as_view(), name="student_course_records"),
    path("lecture/course_detail/<int:course_pk>/<str:course_code>/", LectureCourseRecords.as_view(), name="course_detail"),
    path("adminlecturecourse_detail/<int:course_pk>/<str:course_code>/<int:lecture_id>/", LectureCourseRecords.as_view()
         , name="admin_view_lecture_course_detail"),
]

lecture/models.py
from django.db import models
from accounts.models import User
from department.models import Department
from django.shortcuts import reverse


class LectureManager(models.Manager):
    def search(self, query):
        q_str = models.Q(profile__first_name__icontains=query) | models.Q(profile__last_name__icontains=query) | models.Q(
            profile__username__contains=query)
        return self.filter(q_str).filter(profile__is_active=True)


class LectureModel(models.Model):
    profile = models.OneToOneField(User, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    objects = LectureManager()

    # TODO remove programme from lectureModel
    # so lectureModel will have course_set which already has programme relation

    class Meta:
        verbose_name = "Lecture"
        verbose_name_plural = "Lectures"

    def __str__(self):
        return str(self.profile.get_full_name())

    def get_absolute_url(self):
        return reverse("lecture:detail", kwargs={"pk": self.pk})

lecture/forms.py
from .models import LectureModel
from django import forms
from assessment.models import StudentTheoryAnswer, QuestionTypeChoice, CourseModel


class LectureCreateForm(forms.ModelForm):
    class Meta:
        model = LectureModel
        fields = ("department", )


class StudentAnswerMarkForm(forms.ModelForm):

    class Meta:
        model = StudentTheoryAnswer
        fields = ("question", "answer", "score", "lecture_comment")
        widgets = {
            "question": forms.HiddenInput
        }
        labels = {
            "lecture_comment": "Leave a comment (optional)",
        }

    def __init__(self, *args, **kwargs):
        super(StudentAnswerMarkForm, self).__init__(*args, **kwargs)
        self.fields["answer"].widget.attrs["readonly"] = True
        self.fields["answer"].widget.attrs["class"] = "no-user-select"
        self.fields["lecture_comment"].widget.attrs["rows"] = "2"

    def clean_score(self):
        score = self.cleaned_data.get("score")
        question = self.cleaned_data.get("question")
        if score:
            if score > question.max_mark:
                raise forms.ValidationError("score mark(%s) given is greater than this question max score(%s)"
                                            % (score, question.max_mark))
            elif score < 0:
                score = 0
        return score


class FilterForms(forms.Form):
    marked = forms.CharField(widget=forms.CheckboxInput, required=False)
    marking = forms.CharField(widget=forms.CheckboxInput, required=False)
    submitted = forms.CharField(widget=forms.CheckboxInput, required=False, label="Unmarked")
    # pending = forms.CharField(widget=forms.CheckboxInput, required=False)


class QuestionGroupFilterForm(forms.Form):
    course = forms.ModelChoiceField(required=False, queryset=CourseModel.objects.all())
    assessment_type = forms.CharField(widget=forms.Select(choices=[(None, "---------")] + QuestionTypeChoice.choices ),
                                      required=False, initial=None)

    def __init__(self, course_queryset, *args, **kwargs):
        super(QuestionGroupFilterForm, self).__init__(*args, **kwargs)
        self.fields["course"].queryset = course_queryset.all()

lecture/templates/lecture/scripts/mark/mark_detailview.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <div class="row mt-3">
            <div class="col-md-auto">
                <div class="breadcrumb">
                    <a href="{% url 'assessment:all' %}" class="breadcrumb-item">Assessment</a>
                    <a href="{% url 'lecture:scripts_all' %}" class="breadcrumb-item">Scripts</a>
                    <a href="{% url 'lecture:question_group_detail' course_id=question_group.course_id question_group_pk=question_group.pk %}" class="breadcrumb-item">Student Scripts</a>
                </div>
            </div>
        </div>

        <div class="row my-3 my-lg-4">
            <div class="col-md-6 mx-auto">
                <h4 class="text-center">MARK SCRIPTS {{ object.get_title_display|upper }}</h4>
            </div>
        </div>

    {% if question_group.questions_type == "theory" %}
        <div class="row my-3">
            <div class="col-12 mx-auto">
                <div class="card-group">
                    <div class="card">
                        <div class="card-body">
                            <p>Scripts</p>
                            <div class="table-responsive">
                            <table class="table table-borderless">
                                <tr>
                                    <td>Script Marked</td>
                                    <th>{{ marked_count }}</th>
                                </tr>
                                <tr>
                                    <td>Script Unmarked</td>
                                    <th>{{ unmarked_count }}</th>
                                </tr>
                                <tr>
                                    <td>Total Scripts</td>
                                    <th>{{ student_scripts.count }}</th>
                                </tr>
                            </table>
                        </div>
                        </div>

                    </div>
                    <div class="card">
                        <div class="card-body">
                            <p>Marking Scheme</p>
                            <div class="table-responsive">
                                {% with scheme=question_group.theorymarkingscheme %}
                                    <table class="table">
                                        <tr>
                                            <td>Questions</td>
                                            <th>{{ scheme.solution_set.count }}</th>
                                        </tr>
                                        <tr>
                                            <td>Course Master</td>
                                            <th>{{ scheme.lecture }}</th>
                                        </tr>
                                        <tr>
                                            <td>Total Marks</td>
                                            <td>{{ scheme.question_group.total_marks }}</td>
                                        </tr>
                                    </table>
                                    <div class="d-flex justify-content-end">
                                    <small class="text-muted">last modified {{ scheme.updated_at }}</small>
                                    </div>
                                {% endwith %}
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <p>Filter Scripts By:</p>
                            <form method="get">
                                {{ filter_form|crispy }}
                                <hr>
                                <span class="mt-2">Filter: </span>
                                <div class="btn-group">
                                    <button type="submit" class="btn btn-outline-danger btn-sm {% if not filter_on %} active {% endif %}" name="filterOff" value="off">Off</button>
                                    <button type="submit" class="btn btn-outline-success btn-sm {% if filter_on %} active {% endif %}" name="filterOn" value="on">Filter</button>
                                </div>


                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <div class="row">
            <div class="col">
                <form method="get">
                    <div class="input-group">
                        <input type="search" class="form-control" name="scriptSearch" id="" placeholder="Search Scripts" value="{{ scriptSearch|default_if_none:'' }}">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-outline-secondary">Search</button>
                        </div>
                    </div>
                    <small>Search by student index number</small>
                </form>
            </div>

            <div class="col-12">
                {% if scriptSearch %}
                    <p><b>"{{ scriptSearch }}"</b> matches {{ student_scripts.count }} script</p>
                {% endif %}
                <hr>
            </div>
        </div>

        <div class="row my-3 mt-lg-4">
        <div class="table-responsive">
            <table class="table">
                <tr>
                    <th>#</th>
                    <th>Index Number</th>
                    <th>Name</th>
                    <th>Score</th>
                    <th>Script Status</th>
                    <th>Action</th>
                </tr>
                {% for script in student_scripts %}
                    <tr>
                        <th>{{ forloop.counter }}</th>
                        <td>{{ script.student.index_number }}</td>
                        <td>{{ script.student.get_name }}</td>
                        <td>{{ script.score }}</td>
                        <td>{{ script.get_status_display }}</td>
                        <td>
                            <a href="{% url 'lecture:mark_student_script' question_group_id=script.question_group_id scheme_pk=question_group.theorymarkingscheme.pk student__index_number=script.student.index_number student_script_pk=script.pk %}" class="btn btn-outline-primary btn-block">
                                <span class="fa fa-marker mr-2"></span>{% if script.status == "marked" %}remark{% else %}mark{% endif %}</a>
                        </td>
                    </tr>
                {% endfor %}

            </table>
        </div>
    </div>

    {% elif question_group.questions_type == "multichoice" %}
        <div class="row my-3 my-lg-4">
            <div class="col-md-8 col-lg-6 mx-auto text-center">
                <img src="{% static 'icons/artificial_intelligence.svg' %}" alt="artificial_intelligence" class="img-fluid" style="height: 10em">
                <hr>
                <h5>{{ object.get_title_display }} is {{ question_group.get_questions_type_display }} Questions type</h5>
                <h5>Its has been marked by the computer</h5>
                <a href="{% url 'records:lecture_quiz_detail' question_group_pk=question_group.pk question_group_title=question_group.title course_code=question_group.course.code %}" class="btn btn-link">View {{ question_group.get_title_display }} Records</a>
            </div>
        </div>
    {% endif %}

    </div>
{% endblock %}

lecture/templates/lecture/scripts/mark/mark_script.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load questions_group_extra %}

{% block content %}
    <div class="container-fluid">
        <div class="row my-3 my-lg-4">
            <div class="col-md-auto col-lg-6 mx-auto">
                <table class="table">
                    <tr>
                        <td colspan="2" class="text-center"><span class="h5">{{ course_title_code }}</span></td>
                    </tr>
                    <tr>
                        <td>Student Name</td>
                        <td><span class="h5">{{ student.get_name }}</span></td>
                    </tr>
                    <tr>
                        <td>Index Number</td>
                        <td><span class="h5">{{ student.index_number }}</span></td>
                    </tr>
                    <tr>
                        <td>Assessment</td>
                        <td><span class="h5">{{ quiz_title }}</span></td>
                    </tr>
                </table>
            </div>
        </div>

        {% if student_script_formset.errors %}
            <div class="row">
                <div class="col-auto mx-auto">
                    <div class="alert alert-danger"  onclick="window.scrollBy(screen.availHeight/2, screen.availWidth/2)">
                        <p>Please there are some errors in your markings.</p>
                        <hr>
                        <span>Scroll down <i class="fa fa-chevron-circle-down"></i> to address the issues</span>
                    </div>
                </div>
            </div>
        {% endif %}


        <form method="post">
            {% csrf_token %}

            <div class="row">
                <div class="col-md-6 mb-2">
                    <p class="text-center h5">Student Scripts</p>
                    {{ student_script_formset.management_form }}
                    <div class="table-responsive"  style="height: 80vh; overflow-y: auto;">
                        {% for answer_form in student_script_formset %}
                            <div class="card mb-3 card-hover-shadow">
                                <div class="card-body">
                                        <a href="#goto_{{ answer_form.question.value }}" class="text-decoration-none text-dark" id="goto{{ answer_form.question.value }}_quz">
                                            <div class="d-flex flex-column">
                                                {{ answer_form.question|question_text }}
                                            </div>
                                        </a>
                                </div>
                                <div class="card-body">
                                    <td>{{ answer_form|crispy }}</td>
                               </div>
                            </div>
                        {% endfor %}
                    </div>

                </div>
                <div class="col-md-6  mb-2">
                    <p class="text-center h5">Marking Scheme</p>
                    <div class="d-flex flex-column"  style="height: 80vh; overflow-y: auto;">
                        <div class="table-responsive">
                            {% for solution in lecture_scheme.solution_set.all %}
                                <div class="card card-hover-shadow mb-2">
                                    <div class="card-body">
                                            <div class="d-flex justify-content-between">
                                                <span>Question {{ solution.question.question_number }}</span>
                                                <span>{{ solution.question.max_mark|floatformat:2 }} marks</span>
                                            </div>
                                            
                                            <div class="">
                                                <a href="#goto{{ solution.question.pk }}_quz" class="text-decoration-none text-dark">
                                                    {{ solution.question|linebreaksbr }}
                                                </a>
                                            </div> 
                                    </div>
                                    
                                    <div id="goto_{{ solution.question.id }}" class="card-body">
                                        <p>Lecture Solution</p>
                                        <p class="text-success p-2 rounded" style="background-color: #d4edda5c;">{{ solution.answer|linebreaksbr }}</p>
                                        {% if solution.notes %}
                                            <p><b>Lecture Note</b></p>
                                            <p class="alert bg-light">{{ solution.notes|linebreaksbr|default:"No Note" }}</p>
                                        {% endif %}
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>

            <div class="row my-3 p-2" style=" box-shadow: rgb(0 0 0 / 8%) 0px -11px 10px 4px;">
                <div class="col-lg-8 mx-auto">
                    <button class="btn btn-primary btn-block">Save Marking</button>
                </div>
            </div>
        </form>

    </div>
{% endblock %}