chat/urls.py
from .views import (
    MessagesCreateView, ChatTemplateView, IndividualChatsTemplateView,
    ChatHistoryRedirectView, CourseMassageChat, ChatPeopleTemplateView,
    SelectedDepartmentProgrammeLevel,
    )
from django.urls import path


app_name = "chat"
urlpatterns = [
    path("start/messaging<slug:to_user_slug>", MessagesCreateView.as_view(), name="start_message"),
    path("add/message<slug:to_user_slug>", ChatHistoryRedirectView.as_view(), name="add_message"),
    path("", ChatTemplateView.as_view(), name="home"),
    path("individualschats/", IndividualChatsTemplateView.as_view(), name="individual_chats"),
    path("individualschats/<int:programme_id>/<int:level_pk>", IndividualChatsTemplateView.as_view(), name="individual_chats4lecture"),
    path("individualchats/<slug:current_user_slug>/", IndividualChatsTemplateView.as_view(), name="individualchats_user"),
    path("individualchats/<slug:current_user_slug>/<int:programme_id>/<int:level_pk>", IndividualChatsTemplateView.as_view(), name="individualchats_user_4lecture"),
    path("course/<int:course_id>/", CourseMassageChat.as_view(), name="course_message"),
    path("course/people/<str:course_code>/", ChatPeopleTemplateView.as_view(), name="course_people"),
    path("individualselection/", SelectedDepartmentProgrammeLevel.as_view(), name="individual_filter_selection"),
]

course/urls.py
from django.urls import path
from .views import (
    CourseCreateView, CourseDetailView, CourseDeleteView,
    CourseUpdateView, LectureCourseListView, CourseAssignmentView,
    CourseUnassignmentView, SelectCourseToChatInView, LevelCreateView, LevelListViewView,
    LevelDetailView, LevelUpdateView, LevelDeleteView
)


app_name = "course"
urlpatterns = [
    path("add/", CourseCreateView.as_view(), name="add"),
    path("<str:courseName>/<int:pk>/", CourseDetailView.as_view(), name="detail"),
    path("delete/<str:courseName>/<int:pk>/<int:course_programme_pk>", CourseDeleteView.as_view(), name="delete"),
    path("update/<str:courseName>/<int:pk>/", CourseUpdateView.as_view(), name="update"),
    path("lecturecourses/", LectureCourseListView.as_view(), name="for_lecturer"),
    path("lecturecourses/bbhod/<int:lecturer_pk>/", LectureCourseListView.as_view(), name="lecturer_courses"),

    # hod and admin
    path("assignment/forlecturer/<int:lecturer_pk>/", CourseAssignmentView.as_view(), name="assigment"),
    path("unassignment/fromlecturer/<str:course_code>/", CourseUnassignmentView.as_view(),
         name="unassignment"),
    path("selecttochat/", SelectCourseToChatInView.as_view(), name="select_to_chat"),

    # level
    path("level/listall/", LevelListViewView.as_view(), name="level_list"),
    path("level/addnewone/", LevelCreateView.as_view(), name="level_add"),
    path("level/detail/<int:pk>", LevelDetailView.as_view(), name="level_detail"),
    path("level/update/<int:pk>", LevelUpdateView.as_view(), name="level_update"),
    path("level/delete/<int:pk>", LevelDeleteView.as_view(), name="level_delete"),

]

eAssessmentSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from .view import LandingPage, AboutTemplatePage, SupportTemplatePage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPage.as_view(), name="landing-page"),
    path('about/', AboutTemplatePage.as_view(), name="about-page"),
    path('support/', SupportTemplatePage.as_view(), name="support-page"),
    path("accounts/", include("accounts.urls")),
    path("student/", include("student.urls")),
    path("department/", include("department.urls")),
    path("lecture/", include("lecture.urls")),
    path("assessment/", include("assessment.urls")),
    path("records/", include("record.urls")),
    path("settings/", include("setting.urls")),
    path("chat/", include("chat.urls")),

]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lecture/urls.py
from django.urls import path
from .views import (
    LectureCreateView, LectureDetailView, lecture_created_view, LectureListView,
    LectureStudentScripts, QuizTemplateView, OnGoingQuizTemplateView, QuestionGroupDetailView,
    TheoryMarkingSchemeDetailView, TheoryQuestionSolution, TheoryQuestionSolutionUpdateView,
    TheoryMarkingSchemeHomeTemplateView, MarkTheoryScriptsDetailView, MarkScriptView,
    DepartmentLecturesTemplateView,
)

app_name = "lecture"
urlpatterns = [
    path("add/", LectureCreateView.as_view(), name="add"),
    path("created/", lecture_created_view, name="created"),
    path("detail/<int:pk>/", LectureDetailView.as_view(), name="detail"),
    path("list/", LectureListView.as_view(), name="list"),

    path("assessment/scripts/all/", LectureStudentScripts.as_view(), name="scripts_all"),
    path("assessment/quiz/all/", QuizTemplateView.as_view(), name="quiz_all"),
    path("assessment/quiz/on_going/", OnGoingQuizTemplateView.as_view(), name="on_going_quiz"),
    path("assessment/quiz/detial/<int:question_group_pk>/<int:course_id>/", QuestionGroupDetailView.as_view(), name="question_group_detail"),

    path("assessment/scheme/home/", TheoryMarkingSchemeHomeTemplateView.as_view(), name="scheme_home"),
    path("assessment/scheme/theory/detail/<str:course_id>/<int:question_group_pk>/", TheoryMarkingSchemeDetailView.as_view(), name="theory_scheme_detail"),
    path("assessment/scheme/theory/add/solution/<str:course_id>/<int:question_id>/<int:question_group_id>/<int:scheme_pk>/", TheoryQuestionSolution.as_view(), name="theory_solution_create"),
    path("assessment/scheme/theory/update/solution/<str:course_id>/<int:question_id>/<int:question_group_id>/<int:scheme_id>/<int:solution_pk>/", TheoryQuestionSolutionUpdateView.as_view(), name="theory_solution_update"),

    # marking
    path("assessment/mark/scrpts/<str:question_group_title>/<str:question_group_pk>/", MarkTheoryScriptsDetailView.as_view(), name="mark_scripts"),
    path("assessment/mark/<str:student__index_number>/<int:question_group_id>/<int:student_script_pk>/<int:scheme_pk>/", MarkScriptView.as_view(), name="mark_student_script"),

    # HOD
    path("in/<str:department_name>", DepartmentLecturesTemplateView.as_view(), name="department_lecture"),
]

record/urls.py
from django.urls import path
from .views import (RecordsView, StudentRecordTemplateView,
                    LectureRecordsTemplateView, LectureQuizRecordDetailView, PublishRecordsDetailView,
                    StudentRecordsTemplateView, LectureCourseRecords
                    )


app_name = "records"

urlpatterns = [
    path("all/", RecordsView.as_view(), name="all"),
    path("student/", StudentRecordTemplateView.as_view(), name="student"),
    path("lecture/all/", LectureRecordsTemplateView.as_view(), name="lecture_all"),
    path("lecture/course/<str:course_code>/<int:question_group_pk>/<str:question_group_title>/",
         LectureQuizRecordDetailView.as_view(), name="lecture_quiz_detail"),
    path("publish/<str:question_group_title>/<int:question_group_pk>/<str:course_code>/",
         PublishRecordsDetailView.as_view(), name="publish"),
    path("student/<str:course_code>/<int:course_id>", StudentRecordsTemplateView.as_view(), name="student_course_records"),
    path("lecture/course_detail/<int:course_pk>/<str:course_code>/", LectureCourseRecords.as_view(), name="course_detail"),
    path("adminlecturecourse_detail/<int:course_pk>/<str:course_code>/<int:lecture_id>/", LectureCourseRecords.as_view()
         , name="admin_view_lecture_course_detail"),
]

course/models.py
from django.db import models
from django.shortcuts import reverse
from programme.models import Programme
from lecture.models import LectureModel
from django.utils.text import slugify

class CourseManager(models.Manager):
    def get_lecture_courses(self, lecture, programme=None):
        if programme and lecture:
            # return self.filter(lecture=lecture, programme=programme, semester=lecture.profile.generalsetting.semester)
            return self.filter(lecture=lecture, programme=programme)
        elif lecture:
            # return self.filter(lecture=lecture, semester=lecture.profile.generalsetting.semester)
            return self.filter(lecture=lecture)


class CourseLevel(models.Model):
    """
    The Level can be to access a course.
    example: Level 100 students has their core and objective course
    """
    name = models.CharField(max_length=10, verbose_name="Level name", default="Level",
                            help_text="The letter part of the level")
    number = models.IntegerField(unique=True, verbose_name="Level Number", help_text="The numeric part of the level")

    class Meta:
        verbose_name = "Level"
        verbose_name_plural = "Levels"
        unique_together = ("name", "number")
        ordering = ("name", "number",)

    def __str__(self):
        return "%s %s" % (self.name.title(), self.number)
    
    def get_students(self):
        return self.student_set.count()

    def get_absolute_url(self):
        return reverse("department:programme:course:level_detail", kwargs={"pk": self.pk})

    def get_absolute_update_url(self):
        return reverse("department:programme:course:level_update", kwargs={"pk": self.pk})

    def get_absolute_delete_url(self):
        return reverse("department:programme:course:level_delete", kwargs={"pk": self.pk})


class CourseSemester(models.TextChoices):
    """
    Two semesters in every institution (at least 2).
    """
    SEMESTER1 = "s1", "First Semester"
    SEMESTER2 = "s2", "Second Semester"


class CourseModel(models.Model):
    name = models.CharField(max_length=250)
    code = models.CharField(max_length=100, unique=True, verbose_name="Course code")
    level = models.ForeignKey(CourseLevel, on_delete=models.CASCADE)
    semester = models.CharField(max_length=10, choices=CourseSemester.choices)
    programme = models.ForeignKey(Programme, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    lecture = models.ForeignKey(LectureModel, on_delete=models.CASCADE, null=True, blank=True)
    objects = CourseManager()

    class Meta:
        verbose_name = "Course"
        verbose_name_plural = "Courses"
        ordering = ("level", "name")

    def question_conduct(self):
        return self.conducted_quizzes()

    def __str__(self):
        return "%s (%s)" % (self.name, self.code)

    def conducted_quizzes(self):
        # return question group and join lecture GeneralSetting where academic_year is the same
        if self.lecture:
            return self.questiongroup_set.filter(status__in=("conducted", "published"), academic_year=self.lecture.profile.generalsetting.academic_year)
        else:
            return None

    def get_absolute_url(self):
        return reverse("department:programme:course:detail", kwargs={"courseName": slugify(self.name), "pk": self.pk})

    def get_update_url(self):
        return reverse("department:programme:course:update", kwargs={"courseName": slugify(self.name), "pk": self.pk})

    def get_student_studying(self):
        return self.programme.student_set.filter(level=self.level, profile__generalsetting__semester=self.semester)

lecture/models.py
from django.db import models
from accounts.models import User
from department.models import Department
from django.shortcuts import reverse


class LectureManager(models.Manager):
    def search(self, query):
        q_str = models.Q(profile__first_name__icontains=query) | models.Q(profile__last_name__icontains=query) | models.Q(
            profile__username__contains=query)
        return self.filter(q_str).filter(profile__is_active=True)


class LectureModel(models.Model):
    profile = models.OneToOneField(User, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    objects = LectureManager()

    # TODO remove programme from lectureModel
    # so lectureModel will have course_set which already has programme relation

    class Meta:
        verbose_name = "Lecture"
        verbose_name_plural = "Lectures"

    def __str__(self):
        return str(self.profile.get_full_name())

    def get_absolute_url(self):
        return reverse("lecture:detail", kwargs={"pk": self.pk})

lecture/forms.py
from .models import LectureModel
from django import forms
from assessment.models import StudentTheoryAnswer, QuestionTypeChoice, CourseModel


class LectureCreateForm(forms.ModelForm):
    class Meta:
        model = LectureModel
        fields = ("department", )


class StudentAnswerMarkForm(forms.ModelForm):

    class Meta:
        model = StudentTheoryAnswer
        fields = ("question", "answer", "score", "lecture_comment")
        widgets = {
            "question": forms.HiddenInput
        }
        labels = {
            "lecture_comment": "Leave a comment (optional)",
        }

    def __init__(self, *args, **kwargs):
        super(StudentAnswerMarkForm, self).__init__(*args, **kwargs)
        self.fields["answer"].widget.attrs["readonly"] = True
        self.fields["answer"].widget.attrs["class"] = "no-user-select"
        self.fields["lecture_comment"].widget.attrs["rows"] = "2"

    def clean_score(self):
        score = self.cleaned_data.get("score")
        question = self.cleaned_data.get("question")
        if score:
            if score > question.max_mark:
                raise forms.ValidationError("score mark(%s) given is greater than this question max score(%s)"
                                            % (score, question.max_mark))
            elif score < 0:
                score = 0
        return score


class FilterForms(forms.Form):
    marked = forms.CharField(widget=forms.CheckboxInput, required=False)
    marking = forms.CharField(widget=forms.CheckboxInput, required=False)
    submitted = forms.CharField(widget=forms.CheckboxInput, required=False, label="Unmarked")
    # pending = forms.CharField(widget=forms.CheckboxInput, required=False)


class QuestionGroupFilterForm(forms.Form):
    course = forms.ModelChoiceField(required=False, queryset=CourseModel.objects.all())
    assessment_type = forms.CharField(widget=forms.Select(choices=[(None, "---------")] + QuestionTypeChoice.choices ),
                                      required=False, initial=None)

    def __init__(self, course_queryset, *args, **kwargs):
        super(QuestionGroupFilterForm, self).__init__(*args, **kwargs)
        self.fields["course"].queryset = course_queryset.all()

course/templates/course/lecture/courses.html
{% extends 'base.html' %}


{% block content %}
    <div class="container">
        <div class="row my-3">
            <div class="col text-center">
                <h5 title="{{ lecturer|default:request.user }}">List Of Courses the {{ lecturer.get_short_name|default:request.user.get_short_name }} Handle </h5>
                <p class="text-center" title="The lecturer's">Courses in {{ semester }}</p>
                {% if lecturer and not lecturer.profile.is_hod %}
                    <hr>
                    <div class="d-flex justify-content-end">
                        <a href="{% url 'department:programme:course:assigment' lecturer_pk=lecturer.pk %}?back={{ request.path }}" class="btn btn-primary" onclick="spinOnClick(this)"><span class="fa fa-plus"></span> Assign Course</a>
                    </div>
                {% endif %}
                <hr>
            </div>
        </div>

        {% if coursemodel_list or object_list %}

            <div class="row">
                <div class="col">
                    <form action="" method="get">
                        <div class="form-group">
                            <div class="input-group">
                                <input type="search" name="searchCourse" id="" class="form-control" placeholder="Search course by name or code" value="{{ searchCourse|default:'' }}">
                                <div class="input-group-append">
                                    <button type="submit" onclick="spinOnClick(this)" class="btn btn-secondary">Search</button>
                                </div>
                            </div>

                            {% if searchCourse %}
                                <small>"<b>{{ searchCourse }}</b>" matches {{ courses_list.count }} courses</small><br>
                                <hr>
                            {% endif %}

                        </div>
                    </form>
                </div>
            </div>

            <div class="row my-3">

                {% for course in courses_list %}
                    <div class="col-md-6 col-lg-4 my-3">
                        <div class="card h-100 card-hover-shadow">
                            <div class="card-body">
                                <h6 class="text-center">{{ course.name }}</h6>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                    <small>Course Code</small> <br>
                                    <p>{{ course.code }}</p>
                                </li>
                                <li class="list-group-item">
                                    <small>Quizzes</small>
                                    <p>{{ course.conducted_quizzes.count }}</p>
                                </li>
                                <li class="list-group-item">
                                    <small>Programme</small>
                                    <p>{{ course.programme }}</p>
                                </li>
                                <li class="list-group-item">
                                    <small>Department</small>
                                    <p>{{ course.programme.department }}</p>
                                </li>
                            </ul>
                            <div class="card-footer">
                                <div class="d-flex justify-content-between">
                                    <span class="text-muted">{{ course.level }}</span>
                                    <div class="">
                                        {% if request.user == course.lecture.profile %}
                                            <a href="{{ course.get_absolute_url }}?back={{ request.path }}" class="btn btn-outline-secondary btn-sm mr-2" onclick="spinOnClick(this)">Quizzes</a>
                                            <a href="{% url 'records:course_detail' course_pk=course.pk course_code=course.code %}?back={{ request.path }}" class="btn btn-outline-secondary btn-sm" onclick="spinOnClick(this)">Records</a>
                                        {% else %}
                                            <a href="{% url 'records:admin_view_lecture_course_detail' course_code=course.code course_pk=course.pk lecture_id=course.lecture.id %}?back={{ request.path }}" class="btn btn-outline-secondary btn-sm" onclick="spinOnClick(this)">Records</a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>


        {% else %}
                <div class="row">
                    <div class="col-md-6 mx-auto">
                        <div class="alert alert-info text-center">
                            <span class="fa fa-exclamation-circle fa-2x"></span>
                            <hr>
                            <h5>{{ lecturer.profile.get_full_name|default:"You" }} have no course registered or assigned </h5>
                        </div>
                    </div>
                </div>

        {% endif %}

    </div>
{% endblock content %}
    