chat/urls.py
from .views import (
    MessagesCreateView, ChatTemplateView, IndividualChatsTemplateView,
    ChatHistoryRedirectView, CourseMassageChat, ChatPeopleTemplateView,
    SelectedDepartmentProgrammeLevel,
    )
from django.urls import path


app_name = "chat"
urlpatterns = [
    path("start/messaging<slug:to_user_slug>", MessagesCreateView.as_view(), name="start_message"),
    path("add/message<slug:to_user_slug>", ChatHistoryRedirectView.as_view(), name="add_message"),
    path("", ChatTemplateView.as_view(), name="home"),
    path("individualschats/", IndividualChatsTemplateView.as_view(), name="individual_chats"),
    path("individualschats/<int:programme_id>/<int:level_pk>", IndividualChatsTemplateView.as_view(), name="individual_chats4lecture"),
    path("individualchats/<slug:current_user_slug>/", IndividualChatsTemplateView.as_view(), name="individualchats_user"),
    path("individualchats/<slug:current_user_slug>/<int:programme_id>/<int:level_pk>", IndividualChatsTemplateView.as_view(), name="individualchats_user_4lecture"),
    path("course/<int:course_id>/", CourseMassageChat.as_view(), name="course_message"),
    path("course/people/<str:course_code>/", ChatPeopleTemplateView.as_view(), name="course_people"),
    path("individualselection/", SelectedDepartmentProgrammeLevel.as_view(), name="individual_filter_selection"),
]

eAssessmentSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from .view import LandingPage, AboutTemplatePage, SupportTemplatePage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPage.as_view(), name="landing-page"),
    path('about/', AboutTemplatePage.as_view(), name="about-page"),
    path('support/', SupportTemplatePage.as_view(), name="support-page"),
    path("accounts/", include("accounts.urls")),
    path("student/", include("student.urls")),
    path("department/", include("department.urls")),
    path("lecture/", include("lecture.urls")),
    path("assessment/", include("assessment.urls")),
    path("records/", include("record.urls")),
    path("settings/", include("setting.urls")),
    path("chat/", include("chat.urls")),

]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

setting/urls.py
from django.urls import path
from .views import GeneralSettingCreateView, GeneralSettingUpdateView, GeneralSettingDetailView, SettingRedirectView


app_name = "setting"
urlpatterns = [
    path("redirect/", SettingRedirectView.as_view(), name="redirect"),
    path("create/", GeneralSettingCreateView.as_view(), name="create"),
    path("createForUser/<int:user_id>/<slug:user_slug>", GeneralSettingCreateView.as_view(), name="createForOther"),
    path("update/<int:user_id>/<int:pk>/", GeneralSettingUpdateView.as_view(), name="update"),
    path("detail/<int:user_id>/<int:pk>/", GeneralSettingDetailView.as_view(), name="detail"),
]

student/urls.py
from .views import (StudentCreateView, SuccessfulStudentRegistration, StudentListView, StudentDetailView,
                    LectureStudentsListView, HODStudentTemplateView, ProgrammeLevelStudentTemplateView
                    )
from django.urls import path

app_name = "student"
urlpatterns = [
   path("register/", StudentCreateView.as_view(), name="register"),
   path("registered/", SuccessfulStudentRegistration.as_view(), name="registered"),
   path("list/", StudentListView.as_view(), name="list"),
   path("list/lectureStudent/", LectureStudentsListView.as_view(), name="listLectureStudent"),
   path("detail/<int:pk>/", StudentDetailView.as_view(), name="detail"),

    # hod
    path("hod/group/", HODStudentTemplateView.as_view(), name="group_4_hod"),
    path("hod/group/<int:level_id>/<int:programme_id>", ProgrammeLevelStudentTemplateView.as_view(), name="programme_level_4_hod"),
]

course/models.py
from django.db import models
from django.shortcuts import reverse
from programme.models import Programme
from lecture.models import LectureModel
from django.utils.text import slugify

class CourseManager(models.Manager):
    def get_lecture_courses(self, lecture, programme=None):
        if programme and lecture:
            # return self.filter(lecture=lecture, programme=programme, semester=lecture.profile.generalsetting.semester)
            return self.filter(lecture=lecture, programme=programme)
        elif lecture:
            # return self.filter(lecture=lecture, semester=lecture.profile.generalsetting.semester)
            return self.filter(lecture=lecture)


class CourseLevel(models.Model):
    """
    The Level can be to access a course.
    example: Level 100 students has their core and objective course
    """
    name = models.CharField(max_length=10, verbose_name="Level name", default="Level",
                            help_text="The letter part of the level")
    number = models.IntegerField(unique=True, verbose_name="Level Number", help_text="The numeric part of the level")

    class Meta:
        verbose_name = "Level"
        verbose_name_plural = "Levels"
        unique_together = ("name", "number")
        ordering = ("name", "number",)

    def __str__(self):
        return "%s %s" % (self.name.title(), self.number)
    
    def get_students(self):
        return self.student_set.count()

    def get_absolute_url(self):
        return reverse("department:programme:course:level_detail", kwargs={"pk": self.pk})

    def get_absolute_update_url(self):
        return reverse("department:programme:course:level_update", kwargs={"pk": self.pk})

    def get_absolute_delete_url(self):
        return reverse("department:programme:course:level_delete", kwargs={"pk": self.pk})


class CourseSemester(models.TextChoices):
    """
    Two semesters in every institution (at least 2).
    """
    SEMESTER1 = "s1", "First Semester"
    SEMESTER2 = "s2", "Second Semester"


class CourseModel(models.Model):
    name = models.CharField(max_length=250)
    code = models.CharField(max_length=100, unique=True, verbose_name="Course code")
    level = models.ForeignKey(CourseLevel, on_delete=models.CASCADE)
    semester = models.CharField(max_length=10, choices=CourseSemester.choices)
    programme = models.ForeignKey(Programme, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    lecture = models.ForeignKey(LectureModel, on_delete=models.CASCADE, null=True, blank=True)
    objects = CourseManager()

    class Meta:
        verbose_name = "Course"
        verbose_name_plural = "Courses"
        ordering = ("level", "name")

    def question_conduct(self):
        return self.conducted_quizzes()

    def __str__(self):
        return "%s (%s)" % (self.name, self.code)

    def conducted_quizzes(self):
        # return question group and join lecture GeneralSetting where academic_year is the same
        if self.lecture:
            return self.questiongroup_set.filter(status__in=("conducted", "published"), academic_year=self.lecture.profile.generalsetting.academic_year)
        else:
            return None

    def get_absolute_url(self):
        return reverse("department:programme:course:detail", kwargs={"courseName": slugify(self.name), "pk": self.pk})

    def get_update_url(self):
        return reverse("department:programme:course:update", kwargs={"courseName": slugify(self.name), "pk": self.pk})

    def get_student_studying(self):
        return self.programme.student_set.filter(level=self.level, profile__generalsetting__semester=self.semester)

student/models.py
from django.db import models
from accounts.models import User
from course.models import CourseLevel
from programme.models import Programme
from django.shortcuts import reverse


class StudentManager(models.Manager):
    def create_student(self, first_name: str, last_name: str, phone_number, email, dob, index_number, level):
        profile = User.objects.create_user(
            first_name=first_name, last_name=last_name, phone_number=phone_number, email=email, dob=dob,
            username=index_number,
        )
        student = self.create(index_number=index_number, profile=profile)

        return student

    def search(self, query):
        query = query or ""
        query_str = models.Q(index_number__icontains=query) | models.Q(profile__first_name__icontains=query) | models.Q(
            profile__last_name__icontains=query)
        return self.filter(query_str, profile__is_active=True)

    def search_lecture_student(self, query, lecture):
        if lecture and query:
            query_str = models.Q(index_number__icontains=query) | models.Q(profile__first_name__icontains=query) | models.Q(
                profile__last_name__icontains=query)
            return self.filter(query_str)
        elif lecture:
            query_str = models.Q(programme__department=lecture.department)
            return self.filter(query_str, programme__department=lecture.department)
        else:
            return set()


class Student(models.Model):
    """
    :profile student profile detail including first and last name, phone number, etc
    :index_number student index number unique to every student
    :created_by the staff who added this student to the system

    student model will be added to department: department references the student
    """
    # TODO add student related fields (assessment profile, )
    profile = models.OneToOneField(User, unique=True, on_delete=models.CASCADE)
    index_number = models.CharField(max_length=60, unique=True, null=False, blank=False)
    programme = models.ForeignKey(Programme, on_delete=models.CASCADE, null=True)
    update = models.DateField(auto_now=True)
    level = models.ForeignKey(CourseLevel, on_delete=models.CASCADE)
    objects = StudentManager()

    class Meta:
        ordering = ("programme", "level", "profile__first_name", "profile__last_name", "index_number")

    def get_name(self):
        return self.profile.get_full_name()

    @property
    def quiz_counts(self):
        return self.multichoicescripts_set.count() + self.studenttheoryscript_set.count()

    def __str__(self):
        return self.index_number

    def get_absolute_url(self):
        return reverse("student:detail", kwargs={"pk": self.pk})

    def get_quiz_script_score(self, question_group_pk: int, q_title: str, quiz_type):
        try:
            score = 0
            if quiz_type == "multichoice":
                score = self.multichoicescripts_set.get(
                    question_group_id=question_group_pk,
                    question_group__title=q_title,
                )
                s1 = score.score
                if s1 is None:
                    s1 = score.score_student()
                score = s1
            elif quiz_type == "theory":
                score = self.studenttheoryscript_set.get(
                    question_group_id=question_group_pk,
                    question_group__title=q_title,
                ).total_score
        except models.ObjectDoesNotExist:
            return "---"

        else:
            try:
                return round(score, 2)
            except TypeError as err:
                print(err)
                return "Not marked - %s question" % quiz_type

    def get_course_total_score(self, course_code, course_semester):
        theory = self.studenttheoryscript_set.filter(question_group__course__code=course_code,
                                                       question_group__course__semester=course_semester
                                                       ).aggregate(total_score=models.Sum("total_score")).get("total_score")

        multichoice = self.multichoicescripts_set.filter(
            course__code=course_code,
            course__semester=course_semester
        ).aggregate(total_score=models.Sum("score")).get("total_score")

        if theory and multichoice:
            return round(theory + multichoice, 2)
        elif theory is not None:
            return round(theory, 2)
        elif multichoice is not None:
            return round(multichoice, 2)
        else:
            return "---"

student/templates/student/detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-auto mx-auto mt-3">
                <p class="display-4 text-center">{{ profile.get_full_name }} Detail</p>
            </div>
        </div>

        
        {% if generalsetting_error %}
            <div class="row">
                <div class="col">
                    <div class="alert alert-warning">
                        <p>This student has not setup his or her semester and academic year. <br>
                            <span>This means he or she has not done anything after registeration or has not attend any assessment yet.</span><br>
                        </p>
                        <a href="{% url 'setting:createForOther' user_id=profile.id user_slug=profile.slug %}?next={{ request.path }}" class="btn btn-primary" onclick="appendSpinOnClick(this)"><span class="fa fa-cog"></span> Configure this student settings</a>

                    </div>
                </div>
            </div>
        {% endif %}
            
    </div>



    <div class="container">

        <div class="row">
            <div class="col">
                  <div class="card-group">
                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <p class="text-center">Student Profile</p>
                                <table class="table">
                                    <tr>
                                        <td>First Name</td>
                                        <td>{{ profile.first_name|title }}</td>
                                    </tr>
                                    <tr>
                                        <td>Last Name</td>
                                        <td>{{ profile.last_name|title }}</td>
                                    </tr>
                                    <tr>
                                        <td>Phone number</td>
                                        <td>{{ profile.phone_number|title }}</td>
                                    </tr>
                                    <tr>
                                        <td>Email address</td>
                                        <td>{{ profile.email|default:"---------" }}</td>
                                    </tr>
                                    <tr>
                                        <td>Date Joined</td>
                                        <td>{{ profile.timestamp }}</td>
                                    </tr>
                                    </table>
                            </div>
                        </div>
                    </div>
                    
                    <div class="card">
                        <div class="card-body">
                            <p class="text-center">Student Information</p>
                            <div class="table-responsive">
                                <table class="table">
                                    <tr>
                                        <td>Index Number</td>
                                        <td>{{ student.index_number }}</td>
                                    </tr>
                                    <tr>
                                        <td>Level</td>
                                        <td>{{ student.level }}</td>
                                    </tr>
                                    <tr>
                                        <td>Department</td>
                                        <td>{{ student.programme.department }} </td>
                                    </tr>
                                    <tr>
                                        <td>Programme</td>
                                        <td>{{ student.programme }}</td>
                                    </tr>
                                <tr>
                                    <td>Permission status</td>
                                    <td>
                                        <span class = "badge badge-pill p-2 {% if profile.is_active %} alert-success {% else %} alert-danger {% endif %}" title="Is user active?">Active {{ profile.is_active|yesno|title }}</span>
                                        <span class = "badge badge-pill p-2 {% if profile.student %} alert-success {% else %} alert-danger {% endif %}" title="Is user student?">Student {{ profile.student|yesno|title }}</span>
                                    
                                    </td>
                                </tr>                                    
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
                
            </div>
        </div>

        
        <div class="row my-3">
            

            <div class="col">
                <div class="card-group">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="text-center">Student Semester Course</h5>
                            <div class="table-responsive">
                                <table class="table">
                                    <tr>
                                        <th>Name</th>
                                        <th>Code</th>
                                        <th>Lecture</th>
                                    </tr>
                                    
                                    {% if courses %}
                                        {% for course in courses %}
                                            <tr class="hover-inset">
                                                <td>{{ course.name }}</td>
                                                <td>{{ course.code }}</td>
                                                <td>{{ course.lecture }}</td>
                                            </tr>
                                        {% endfor %}
                                    
                                    {% else %}
                                        <tr>
                                            <td colspan="3">
                                                <div class="alert alert-secondary">
                                                    <p class="text-center">
                                                        <span class="badge badge-pill badge-info p-1">{{ student.programme }}</span> 
                                                        <span class="badge badge-pill badge-info p-1">{{ student.level }}</span>
                                                        <span class="badge badge-pill badge-info p-1">{{ student.profile.generalsetting.get_semester_display }}</span>   has no courses registered</p>
                                                </div>
                                            </td>
                                        </tr>
                                    {% endif %}
                                    
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>

     

    </div>
{% endblock %}

student/templates/student/lecture_all_student.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
    {% if has_student %}
        <div class="row d-print-none">
            <div class="col-12 mx-auto mt-3">
                <h5 class="text-center">All Registered Student</h5>
                <hr>
            </div>
            <div class="col-12 mb-3">
                <form action="" method="get">
                    <div class="input-group">
                        <input type="search" class="form-control" value="{{ query|default_if_none:"" }}" placeholder="find by student name or index number" name="query">
                        <div class="input-group-append">
                            <button class="btn btn-outline-primary" type="submit" title="Find" aria-label="Find"><span class="fa fa-search"></span></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="row d-print-none">
            <div class="col-md-12">
                {% if query %}
                    {% if student_list.count > 1 %}
                        <p>"{{ query }}" matches {{ student_list.count }} students</p>
                    {% else %}
                        <p>"{{ query }}" matches {{ student_list.count }} students</p>
                    {% endif %}
                {% else %}
                    <p>Showing total of <b>{{ student_list.count|default:"0" }}</b> registered student in {{ request.user.lecturemodel.department|default:"the" }} Department</p>
                {% endif %}
                <hr>
            </div>
    </div>

        {% regroup student_list by programme as student_programmes %}
        {% for student_programme in student_programmes %}
            <div class="row my-3">
                <div class="table-responsive">
                    <h5>{{ student_programme.grouper }} </h5>
                    <hr>
                    {% regroup student_programme.list by level as student_progs_by_lvl %}
                    {% for std_lst in student_progs_by_lvl %}
                        <table class="table table-bordered">
                            <tr>
                                <th colspan="5">{{ std_lst.grouper }}</th>
                            </tr>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Index Number</th>
                                <th>Level</th>
                                <th>Programme</th>
                            </tr>
                            {% for student in std_lst.list %}
                                <tr class="hover-inset">
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ student.get_name }}</td>
                                    <td><a href="{{ student.get_absolute_url }}" class="btn-link">{{ student.index_number }}</a></td>
                                    <td>{{ student.level }}</td>
                                    <td>{{ student.programme|default_if_none:"---" }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}

    {% else %}
        <div class="row " style="margin-top: 20vh;">
            <div class="col-md-6 mx-auto">
                <div class="alert alert-info text-center">
                    <p class="lead text-center">{{ request.user.first_name }}, your not assigned to any courses yet.</p>
                    <hr>
                    <p><i class="fa fa-exclamation-circle mr-2"></i>Contact the administrator</p>
                </div>
            </div>
        </div>
    {% endif %}
    </div>
{% endblock %}

student/templates/student/listview.html
{% extends 'base.html' %}
{% block content %}
    <div class="container  d-print-none">
        <div class="row">
            <div class="col-12 mx-auto mt-3">
                <h5 class="text-center">All Registered Student</h5>
                <hr>
            </div>
            <div class="col-12 mb-3">
                <form action="" method="get">
                    <div class="input-group">
                        <input type="search" class="form-control" value="{{ query|default_if_none:"" }}" placeholder="find by student name or index number" name="query">
                        <div class="input-group-append">
                            <button class="btn btn-outline-primary" type="submit" title="Find" aria-label="Find"><span class="fa fa-search"></span></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                {% if query %}
                    {% if student_list.count > 1 %}
                        <p>"{{ query }}" matches {{ student_list.count }} students group by programme</p>
                    {% else %}
                        <p>"{{ query }}" matches {{ student_list.count }} students group by programme</p>
                    {% endif %}
                {% else %}
                    <p>Showing total of <b>{{ student_list.count }}</b> registered student group by programme</p>
                {% endif %}
                <hr>
            </div>
        </div>
    </div>

    {% regroup student_list by programme as student_list_group %}
    <div class="container">
    {% for student_group in student_list_group %}
        <div class="">

                <div class="row">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <tr>
                                <td colspan="5" class="text-center">{{ student_group.grouper }} Students</td>
                            </tr>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Index Number</th>
                                <th>Level</th>
                                <th>Programme</th>
                            </tr>
                            {% for student in student_group.list %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td><a href="{{ student.get_absolute_url }}">{{ student.get_name }}</a></td>
                                    <td>{{ student.index_number }}</td>
                                    <td>{{ student.level }}</td>
                                    <td>{{ student.programme|default_if_none:"---" }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>

{% endblock %}

student/templates/student/registered.html
{% extends 'base.html' %}
{% block content %}
    <div class="jumbotron alert alert-success">
        <div class="container my-3 my-lg-4">
            <div class="row">
                <div class="col-md-10 col-lg-8 mx-auto" >
                    <h5>Successfully Registered  <a href="{{ student.profile.get_absolute_url }}" class="alert-link">{{ student.get_name }}</a> to <a href="{{ student.programme.get_absolute_url }}" class="alert-link">{{ student.programme }} Programme</a></h5>
                    <p class="lead">Courses for level {{ student.level }}</p>
                    <hr>
                    <table class="table table-bordered table-success">
                        <tr>
                            <th>#</th>
                            <th>Course Name</th>
                            <th>Course Code</th>
                            <th>Course Master</th>
                            <th>Level</th>
                        </tr>
                        {% for course in student.programme.coursemodel_set.all %}
                            {% if course.level == student.level %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td><a class="alert-link" href="{{ course.get_absolute_url }}">{{ course.name }}</a></td>
                                    <td>{{ course.code }}</td>
                                    <td>{{ course.lecture }}</td>
                                    <td>{{ course.level }}</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </table>
                <div class="btn-group btn-block bg-light">
                    <a  href="{% url 'student:register' %}" class="btn btn-link">Add another</a>
                    <a href="{% url 'student:listLectureStudent' %}" class="btn btn-link">All student</a>
                </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}