accounts/urls.py
from django.urls import path
from .views import (AdminCreateView, UserDetailView, StaffLoginView,
                    AdminLoginView, user_logout, student_login, AddAdminView,
                    UserUpdateView, ConfirmPasswordResetView, ChangePasswordView,
                    ChangePasswordUpdateView, AdminDashBoard
 )
from eAssessmentSystem.view import AdminStaffLogin


app_name = "accounts"

urlpatterns = [
    path("login/staff", StaffLoginView.as_view(), name="staff-login-page"),
    path("login/admin", AdminLoginView.as_view(), name="admin-login-page"),
    path("logout", user_logout, name="logout"),
    path("addAdminWarning", AddAdminView.as_view(), name="add_admin_view"),
    path("profile/<slug:slug>/<int:pk>/", UserDetailView.as_view(), name="user-profile"),
    path("editprofile/<slug:slug>/<int:pk>/", UserUpdateView.as_view(), name="profile_edit"),
    path("login/", AdminStaffLogin.as_view(), name="loginPage"),
    path("addadmin/", AdminCreateView.as_view(), name="admin-add"),
    path("studentLogin/", student_login, name="student_login"),

    path("resetpassword/", ConfirmPasswordResetView.as_view(), name="confirm_reset_pwd"),
    path("changepwdreset/", ChangePasswordView.as_view(), name="change_pwd_reset"),

    path("changeyourpwd/", ChangePasswordUpdateView.as_view(), name="change_pwd_update"),

    path("dashboard/", AdminDashBoard.as_view(), name="admin-dashboard"),
]

chat/urls.py
from .views import (
    MessagesCreateView, ChatTemplateView, IndividualChatsTemplateView,
    ChatHistoryRedirectView, CourseMassageChat, ChatPeopleTemplateView,
    SelectedDepartmentProgrammeLevel,
    )
from django.urls import path


app_name = "chat"
urlpatterns = [
    path("start/messaging<slug:to_user_slug>", MessagesCreateView.as_view(), name="start_message"),
    path("add/message<slug:to_user_slug>", ChatHistoryRedirectView.as_view(), name="add_message"),
    path("", ChatTemplateView.as_view(), name="home"),
    path("individualschats/", IndividualChatsTemplateView.as_view(), name="individual_chats"),
    path("individualschats/<int:programme_id>/<int:level_pk>", IndividualChatsTemplateView.as_view(), name="individual_chats4lecture"),
    path("individualchats/<slug:current_user_slug>/", IndividualChatsTemplateView.as_view(), name="individualchats_user"),
    path("individualchats/<slug:current_user_slug>/<int:programme_id>/<int:level_pk>", IndividualChatsTemplateView.as_view(), name="individualchats_user_4lecture"),
    path("course/<int:course_id>/", CourseMassageChat.as_view(), name="course_message"),
    path("course/people/<str:course_code>/", ChatPeopleTemplateView.as_view(), name="course_people"),
    path("individualselection/", SelectedDepartmentProgrammeLevel.as_view(), name="individual_filter_selection"),
]

eAssessmentSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from .view import LandingPage, AboutTemplatePage, SupportTemplatePage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPage.as_view(), name="landing-page"),
    path('about/', AboutTemplatePage.as_view(), name="about-page"),
    path('support/', SupportTemplatePage.as_view(), name="support-page"),
    path("accounts/", include("accounts.urls")),
    path("student/", include("student.urls")),
    path("department/", include("department.urls")),
    path("lecture/", include("lecture.urls")),
    path("assessment/", include("assessment.urls")),
    path("records/", include("record.urls")),
    path("settings/", include("setting.urls")),
    path("chat/", include("chat.urls")),

]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

setting/urls.py
from django.urls import path
from .views import GeneralSettingCreateView, GeneralSettingUpdateView, GeneralSettingDetailView, SettingRedirectView


app_name = "setting"
urlpatterns = [
    path("redirect/", SettingRedirectView.as_view(), name="redirect"),
    path("create/", GeneralSettingCreateView.as_view(), name="create"),
    path("createForUser/<int:user_id>/<slug:user_slug>", GeneralSettingCreateView.as_view(), name="createForOther"),
    path("update/<int:user_id>/<int:pk>/", GeneralSettingUpdateView.as_view(), name="update"),
    path("detail/<int:user_id>/<int:pk>/", GeneralSettingDetailView.as_view(), name="detail"),
]

setting/models.py
from django.db import models
from course.models import CourseSemester
from accounts.models import User
from django.shortcuts import reverse
from django.utils import timezone

current_year = timezone.now().date().year


class NameOrder(models.TextChoices):
    FIRSTNAME = "f", "First Name"
    LASTNAME = "l", "Last Name"


class GeneralSetting(models.Model):
    semester = models.CharField(max_length=60, choices=CourseSemester.choices,
                                help_text="The current academic semester",
                                default=CourseSemester.SEMESTER1,
                                )
    name_order = models.CharField(max_length=20, choices=NameOrder.choices,
                                  help_text="How to order your name",
                                  default=NameOrder.FIRSTNAME,
                                  )
    academic_year = models.CharField(max_length=11, default=current_year-1,
                                     help_text="Select the academic year for the semester",
                                     )
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)

    def __str__(self):
        return "%s settings " % str(self.user)

    def get_absolute_url(self):
        return reverse("setting:detail", kwargs={"pk": self.id, "user_id": self.user_id})

    def get_update_url(self):
        return reverse("setting:update", kwargs={"pk": self.id, "user_id": self.user_id})

setting/forms.py
from django import forms
from .models import GeneralSetting
import datetime

this_year = datetime.date.today().year
year = tuple(
    (f"{x-1} / {x}", f"{x-1} / {x}") for x in range(this_year, this_year -12, -1)
)


class GeneralSettingUpdateForm(forms.ModelForm):
    class Meta:
        model = GeneralSetting
        exclude = ("user",)

        widgets = {
            "academic_year": forms.Select(choices=year),
        }

setting/views.py
from eAssessmentSystem.tool_utils import is_safe_url
from accounts.models import User
from django.shortcuts import reverse, redirect
from django.views.generic import CreateView, UpdateView, DetailView, RedirectView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import GeneralSetting
from .forms import GeneralSettingUpdateForm


class GeneralSettingUpdateView(LoginRequiredMixin, UpdateView):
    model = GeneralSetting
    form_class = GeneralSettingUpdateForm
    template_name = "settings/create.html"

    def get_context_data(self, **kwargs):
        ctx = super(GeneralSettingUpdateView, self).get_context_data(**kwargs)
        ctx["title"] = "General  Settings"
        return ctx


class GeneralSettingCreateView(LoginRequiredMixin, CreateView):
    model = GeneralSetting
    form_class = GeneralSettingUpdateForm
    template_name = "settings/create.html"

    def get_user(self):
        try:
            user_id = self.kwargs.get("user_id")
            user_slug = self.kwargs.get("user_slug")
            user = User.objects.get(id=user_id, slug=user_slug)
            return user
        except User.DoesNotExist:
            return self.request.user

    def get_context_data(self, **kwargs):
        ctx = super(GeneralSettingCreateView, self).get_context_data(**kwargs)
        user = self.get_user()
        name = "Your" if self.request.user == user else str(user.get_short_name()) + "'s"
        ctx["title"] = "%s General Settings" % name
        return ctx

    def form_valid(self, form):
        user = self.get_user()
        try:
            instance = GeneralSetting.objects.get(user_id=user.id)
            return redirect(instance.get_absolute_url())
        except GeneralSetting.DoesNotExist:
            form.instance.user = user
            
        return super(GeneralSettingCreateView, self).form_valid(form)

    # def form_invalid(self, form):
    #     returns = super(GeneralSettingCreateView, self).form_invalid(form)
    #     return returns

    def get_success_url(self) -> str:
        next_url = self.request.GET.get("next")
        if is_safe_url(next_url, self.request.get_host()):
            return next_url
        return super().get_success_url()


class GeneralSettingDetailView(LoginRequiredMixin, DetailView):
    template_name = "settings/detail.html"
    model = GeneralSetting

    def get_context_data(self, **kwargs):
        ctx = super(GeneralSettingDetailView, self).get_context_data(**kwargs)
        ctx["title"] = "General  Settings"
        return ctx


class SettingRedirectView(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        try:
            return reverse("setting:detail", kwargs=dict(pk=self.request.user.generalsetting.id,
                            user_id=self.request.user.generalsetting.user_id))
        except AttributeError:
            return reverse("setting:create")

setting/templates/settings/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <div class="row mt-3 mt-lg-4">
            <div class="col-md-6 mx-auto">
                <p class="btn-block text-center lead font-weight-bold">{{ title }}</p>
                <hr>
                <div class="card shadow" style="margin-top: 4em">
                    <div class="card-body">
                        <div class="text-center " style="margin-top: -3.7em">
                            <i class="fa fa-cog fa-5x mx-auto text-dark"></i>
                        </div>
                        <form action="" method="post">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button type="submit" class="btn btn-primary btn-block mt-3 mt-lg-4" onclick="spinOnClick(this)">Save</button>
                        </form>
                    </div>
                </div>
                <div class="alert alert-info mt-3 mt-lg-4">
                        <span><span class="fa fa-info-circle mr-2"></span> Change your assessment <i class="fa fa-spin fa-cog"></i> to reflect your academic calendar</span>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

setting/templates/settings/detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                 <h3 class="text-center my-3">Your Settings</h3>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 mx-auto my-3">
                <div class="card h-100 card-hover-shadow">
                    <div class="card-body">
                        <div class="d-flex justify-content-center mb-3">
                            <span class="fa fa-user-cog fa-5x text-warning"></span>
                        </div>
                        <table class="table table-borderless">
                            <tr>
                                <td>Semester</td>
                                <td>{{ generalsetting.get_semester_display }}</td>
                            </tr>
                            <tr>
                                <td>Name Order</td>
                                <td>{{ generalsetting.get_name_order_display }}</td>
                            </tr>
                            <tr>
                                <td>Academic Year</td>
                                <td>{{ generalsetting.academic_year }}</td>
                            </tr>
                        </table>

                    </div>
                    <div class="card-footer bg-transparent">
                        <a href="{{ generalsetting.get_update_url }}" class="btn btn-warning btn-block"
                            onclick="spinOnClick(this)">Change setting <i class="fa fa-cog mr-2"></i></a>
                    </div>
                </div>
            </div>

            <div class="col-md-6 mx-auto my-3">
                <div class="card h-100 card-hover-shadow">
                    <div class="card-body">
                        <div class="d-flex justify-content-center mb-3">
                            <span class="fa fa-user-shield fa-5x text-info"></span>
                        </div>
                        <p><b class="mr-2">Last Profile Update: </b>{{ request.user.updated }}</p>
                        <p><b class="mr-2">Last Login: </b>{{ request.user.last_login }}</p>
                    </div>
                    <div class="card-footer bg-transparent">
                        <a href="{% url 'accounts:change_pwd_update' %}?back={{ request.path }}" class="btn btn-info btn-block">Change password <span class="fa fa-lock"></span></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}